services:
  - type: web
    name: flask-yt-dlp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && pip install yt-dlp
    startCommand: gunicorn main:app
    envVars:
      - key: SECRET_KEY
        value: "124816"
